packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.0
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.6.6
  '@platforma-sdk/model': 1.47.5
  '@platforma-sdk/ui-vue': 1.48.0
  '@platforma-sdk/tengo-builder': 2.4.1
  '@platforma-sdk/package-builder': 3.10.7
  '@platforma-sdk/block-tools': 2.6.27
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.48.1
  '@milaboratories/helpers': 1.12.0

  # Block-specific dependencies
  "@milaboratories/graph-maker": ^1.1.174
  '@milaboratories/software-pframes-conv': ^2.2.9
  "@platforma-open/milaboratories.runenv-python-3": ^1.4.12
  "@platforma-open/milaboratories.software-ptransform": ^1.6.6

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  '@vueuse/core': ^13.3.0
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.7
  'eslint': ^9.25.1
  "sass-embedded": ^1.77.8
  '@changesets/cli': ^2.29.8
