packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.39.0
  "@platforma-sdk/ui-vue": ^1.39.0
  "@platforma-sdk/workflow-tengo": ^4.9.2
  "@platforma-sdk/block-tools": ^2.5.62
  "@platforma-sdk/test": ^1.39.0
  "@platforma-sdk/tengo-builder": ^2.1.12
  "@platforma-sdk/package-builder": ^2.16.2
  "@platforma-sdk/eslint-config": ^1.0.3

  "@milaboratories/graph-maker": 1.1.128
  '@milaboratories/software-pframes-conv': ^2.2.2
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  "@platforma-open/milaboratories.software-ptransform": ^1.5.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  "js-yaml": ^4.1.0
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.2.4
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1
  "sass-embedded": ^1.77.8

  "@changesets/cli": ^2.28.1
