packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.43.21
  "@platforma-sdk/ui-vue": ^1.43.21
  "@platforma-sdk/workflow-tengo": ^5.3.3
  "@platforma-sdk/block-tools": ^2.6.8
  "@platforma-sdk/test": ^1.43.26
  "@platforma-sdk/tengo-builder": ^2.2.2
  "@platforma-sdk/package-builder": ^3.8.0
  "@platforma-sdk/eslint-config": ^1.1.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@milaboratories/graph-maker": ^1.1.165
  '@milaboratories/software-pframes-conv': ^2.2.7
  "@platforma-open/milaboratories.runenv-python-3": ^1.4.12
  "@platforma-open/milaboratories.software-ptransform": ^1.6.5

  '@vueuse/core': ^13.3.0
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.2.4
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1
  "sass-embedded": ^1.77.8

  "@changesets/cli": ^2.28.1
