packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.9
  '@milaboratories/ts-configs': 1.2.1
  '@platforma-sdk/workflow-tengo': 5.8.2
  '@platforma-sdk/model': 1.53.15
  '@platforma-sdk/ui-vue': 1.54.1
  '@platforma-sdk/tengo-builder': 2.4.18
  '@platforma-sdk/package-builder': 3.11.4
  '@platforma-sdk/block-tools': 2.6.52
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.54.4
  '@milaboratories/helpers': 1.13.3

  # Block-specific dependencies
  "@milaboratories/graph-maker": 1.1.224
  '@milaboratories/software-pframes-conv': 2.2.9
  "@platforma-open/milaboratories.runenv-python-3": 1.4.12
  "@platforma-open/milaboratories.software-ptransform": 1.6.6

  # Common dependencies - can use ^ or ~
  '@vueuse/core': ^13.3.0
  'vue': ^3.5.24
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.7
  'shx': ^0.4.0
  'eslint': ^9.25.1
  'sass-embedded': ^1.77.8
  '@changesets/cli': ^2.29.8
